// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwC-tg2E_f6zcmFFIEzlmKqO4xaebbAq4',
    appId: '1:1018926577356:web:9facaa128f169aa720b469',
    messagingSenderId: '1018926577356',
    projectId: 'idream-project',
    authDomain: 'idream-project.firebaseapp.com',
    storageBucket: 'idream-project.appspot.com',
    measurementId: 'G-3JHVST3WDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU7LN3TxGJwWMPN66-apQR63yIdm7lzak',
    appId: '1:1018926577356:android:b9a878ae95680e2120b469',
    messagingSenderId: '1018926577356',
    projectId: 'idream-project',
    storageBucket: 'idream-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb0RIJku97ze7ndPLgKYTLIlgvAOHQkeQ',
    appId: '1:1018926577356:ios:2ca521574db60b5f20b469',
    messagingSenderId: '1018926577356',
    projectId: 'idream-project',
    storageBucket: 'idream-project.appspot.com',
    iosClientId: '1018926577356-dfofnjgjadfh6fsoj7gildoova1ptp1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.iDreamAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb0RIJku97ze7ndPLgKYTLIlgvAOHQkeQ',
    appId: '1:1018926577356:ios:2ca521574db60b5f20b469',
    messagingSenderId: '1018926577356',
    projectId: 'idream-project',
    storageBucket: 'idream-project.appspot.com',
    iosClientId: '1018926577356-dfofnjgjadfh6fsoj7gildoova1ptp1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.iDreamAssessment',
  );
}
